"""Word table

Revision ID: 1a535a33afaa
Revises: 
Create Date: 2018-07-25 21:13:22.873150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a535a33afaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theword', sa.String(length=50), nullable=True),
    sa.Column('dialect', sa.String(length=50), nullable=True),
    sa.Column('translation', sa.String(length=200), nullable=True),
    sa.Column('gram_feat', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_dialect'), 'word', ['dialect'], unique=False)
    op.create_index(op.f('ix_word_gram_feat'), 'word', ['gram_feat'], unique=False)
    op.create_index(op.f('ix_word_theword'), 'word', ['theword'], unique=False)
    op.create_index(op.f('ix_word_translation'), 'word', ['translation'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_translation'), table_name='word')
    op.drop_index(op.f('ix_word_theword'), table_name='word')
    op.drop_index(op.f('ix_word_gram_feat'), table_name='word')
    op.drop_index(op.f('ix_word_dialect'), table_name='word')
    op.drop_table('word')
    # ### end Alembic commands ###
