"""POS

Revision ID: 6b41f1adeefc
Revises: 8c560f730cdc
Create Date: 2018-11-04 20:04:58.853805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b41f1adeefc'
down_revision = '8c560f730cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tanty')
    op.drop_table('grammems')
    op.drop_table('transitivity')
    op.drop_table('drg_forms')
    op.drop_table('drg')
    op.drop_table('urax')
    op.drop_table('lexical_glosses')
    op.drop_table('tanty_forms')
    op.drop_table('urax_forms')
    op.create_index(op.f('ix_part_of_speech_name'), 'part_of_speech', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_of_speech_name'), table_name='part_of_speech')
    op.create_table('urax_forms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('form', sa.NUMERIC(), nullable=True),
    sa.Column('word', sa.INTEGER(), nullable=True),
    sa.Column('grammem', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['grammem'], ['grammems.id'], ),
    sa.ForeignKeyConstraint(['word'], ['urax.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tanty_forms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('form', sa.NUMERIC(), nullable=True),
    sa.Column('word', sa.INTEGER(), nullable=True),
    sa.Column('grammem', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['grammem'], ['grammems.id'], ),
    sa.ForeignKeyConstraint(['word'], ['tanty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('lexical_glosses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gloss', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('urax',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.NUMERIC(), nullable=True),
    sa.Column('alt_spelling_of', sa.INTEGER(), nullable=True),
    sa.Column('pos', sa.INTEGER(), nullable=True),
    sa.Column('transitivity', sa.INTEGER(), nullable=True),
    sa.Column('transitivity_not_sure', sa.INTEGER(), nullable=True),
    sa.Column('lexical_gloss', sa.INTEGER(), nullable=True),
    sa.Column('translation_rus', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['alt_spelling_of'], ['urax.id'], ),
    sa.ForeignKeyConstraint(['lexical_gloss'], ['lexical_glosses.id'], ),
    sa.ForeignKeyConstraint(['pos'], ['part_of_speech.id'], ),
    sa.ForeignKeyConstraint(['transitivity'], ['transitivity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('drg',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.NUMERIC(), nullable=True),
    sa.Column('alt_spelling_of', sa.INTEGER(), nullable=True),
    sa.Column('pos', sa.INTEGER(), nullable=True),
    sa.Column('transitivity', sa.INTEGER(), nullable=True),
    sa.Column('transitivity_not_sure', sa.INTEGER(), nullable=True),
    sa.Column('lexical_gloss', sa.INTEGER(), nullable=True),
    sa.Column('translation_rus', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['alt_spelling_of'], ['drg.id'], ),
    sa.ForeignKeyConstraint(['lexical_gloss'], ['lexical_glosses.id'], ),
    sa.ForeignKeyConstraint(['pos'], ['part_of_speech.id'], ),
    sa.ForeignKeyConstraint(['transitivity'], ['transitivity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('drg_forms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('form', sa.NUMERIC(), nullable=True),
    sa.Column('word', sa.INTEGER(), nullable=True),
    sa.Column('grammem', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['grammem'], ['grammems.id'], ),
    sa.ForeignKeyConstraint(['word'], ['drg.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transitivity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('grammems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.NUMERIC(), nullable=True),
    sa.Column('pos', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pos'], ['part_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tanty',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.NUMERIC(), nullable=True),
    sa.Column('alt_spelling_of', sa.INTEGER(), nullable=True),
    sa.Column('pos', sa.INTEGER(), nullable=True),
    sa.Column('transitivity', sa.INTEGER(), nullable=True),
    sa.Column('transitivity_not_sure', sa.INTEGER(), nullable=True),
    sa.Column('lexical_gloss', sa.INTEGER(), nullable=True),
    sa.Column('translation_rus', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['alt_spelling_of'], ['tanty.id'], ),
    sa.ForeignKeyConstraint(['lexical_gloss'], ['lexical_glosses.id'], ),
    sa.ForeignKeyConstraint(['pos'], ['part_of_speech.id'], ),
    sa.ForeignKeyConstraint(['transitivity'], ['transitivity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
